version: '3.5'
services:
  angular-ui:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: angular-ui
    volumes:
       - ./:/usr/src/app/app-ui
       - /usr/src/app/app-ui/node_modules